apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::298727067888:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1PWH0008U48AS
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::298727067888:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-13T19:56:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "12718"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 075ffad2-b786-4b27-b615-02318c6525c1
