apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::298727067888:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QFT2STZEOS7C
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::298727067888:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-13T12:24:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1783"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 190acaa7-7882-41e9-9b09-1a780c78a5a6
