apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::298727067888:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8W3YF69VBBYG
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::298727067888:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-13T18:42:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1788"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9559bf84-4e4d-4eec-b205-f14f2683cdc6
